In [1]:
# supervised Learning - the data is labelled
import pandas as pd
# Load the data from the CSV file
data= pd.read_csv("E:/data.csv")
data.head(50)
# classification is when the predicted variable is categorical- eg,default/not default, Yes/NO
#Regression will when the predicted variable is Continous- e.g, sales,profits,Time

,Clump,UnifSize,UnifShape,MargAdh,SingEpiSize,BareNuc,BlandChrom,NormNucl,Mit,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
5,8,10,10,8,7,10,9,7,1,4
6,1,1,1,1,2,10,3,1,1,2
7,2,1,2,1,2,1,3,1,1,2
8,2,1,1,1,2,1,1,1,5,2
9,4,2,1,1,2,1,2,1,1,2
10,1,1,1,1,1,1,3,1,1,2
11,2,1,1,1,2,1,2,1,1,2
12,5,3,3,3,2,3,4,4,1,4
13,1,1,1,1,2,3,3,1,1,2
14,8,7,5,10,7,9,5,5,4,4
15,7,4,6,4,6,1,4,3,1,4
16,4,1,1,1,2,1,2,1,1,2
17,4,1,1,1,2,1,3,1,1,2
18,10,7,7,6,4,10,4,1,2,4
19,6,1,1,1,2,1,3,1,1,2
20,7,3,2,10,5,10,5,4,4,4
21,10,5,5,3,6,7,7,10,1,4
22,3,1,1,1,2,1,2,1,1,2
23,8,4,5,1,2,?,7,3,1,4
24,1,1,1,1,2,1,3,1,1,2
25,5,2,3,4,2,7,3,6,1,4
26,3,2,1,1,1,1,2,1,1,2
27,5,1,1,1,2,1,2,1,1,2
28,2,1,1,1,2,1,2,1,1,2
29,1,1,3,1,2,1,1,1,1,2
30,3,1,1,1,1,1,2,1,1,2
31,2,1,1,1,2,1,3,1,1,2
32,10,7,7,3,8,5,7,4,3,4
33,2,1,1,2,2,1,3,1,1,2
34,3,1,2,1,2,1,2,1,1,2
35,2,1,1,1,2,1,2,1,1,2
36,10,10,10,8,6,1,8,9,1,4
37,6,2,1,1,1,1,7,1,1,2
38,5,4,4,9,2,10,5,6,1,4
39,2,5,3,3,6,7,7,5,1,4
40,6,6,6,9,6,?,7,8,1,2
41,10,4,3,1,3,3,6,5,2,4
42,6,10,10,2,8,10,7,3,3,4
43,5,6,5,6,10,1,3,1,1,4
44,10,10,10,4,8,1,8,10,1,4
45,1,1,1,1,2,1,2,1,2,2
46,3,7,7,4,4,9,4,8,1,4
47,1,1,1,1,2,1,2,1,1,2
48,4,1,1,3,2,1,3,1,1,2
49,7,8,7,2,4,8,3,8,2,4

In [2]:
print(data.isnull().sum())# checking empties

Clump          0
UnifSize       0
UnifShape      0
MargAdh        0
SingEpiSize    0
BareNuc        0
BlandChrom     0
NormNucl       0
Mit            0
Class          0
dtype: int64

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


# Features (X) and target (y)
X = data.drop("Class", axis=1)
y = data["Class"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)

ValueError: could not convert string to float: '?'